In [1]:
from ucimlrepo import fetch_ucirepo

In [2]:
# fetch dataset
chronic_kidney_disease = fetch_ucirepo(id=336)

In [3]:
# data (as pandas dataframes)
X = chronic_kidney_disease.data.features
y = chronic_kidney_disease.data.targets

In [4]:
# metadata
print(chronic_kidney_disease.metadata)

{'uci_id': 336, 'name': 'Chronic Kidney Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/336/data.csv', 'abstract': 'This dataset can be used to predict the chronic kidney disease and it can be collected from the hospital nearly 2 months of period.', 'area': 'Other', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 400, 'num_features': 24, 'feature_types': ['Real'], 'demographics': ['Age'], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2015, 'last_updated': 'Mon Mar 04 2024', 'dataset_doi': '10.24432/C5G020', 'creators': ['L. Rubini', 'P. Soundarapandian', 'P. Eswaran'], 'intro_paper': None, 'additional_info': {'summary': 'We use the following representation to collect the dataset\r\n                        age\t\t-\tage\t\r\n\t\t\tbp\t\t-\tblood pressure\r\n\t\t\tsg\t\t-\tspecific gravity\r\n\t\t\tal\t\t-   \talbumin\r\n\t\t\tsu\t\t-\tsugar\r\n\t\t\trbc\t\t-\tred blood cells\r\n\t\t\tpc\t\t-\tpus cell\r\n\t\t\tpcc\t\t-\tpus cell clumps\r\n\t\t\tba\t\t-\tbacteria\r\n\t\t\tbgr\t\t-\tblood glucose random\r\n\t\t\tbu\t\t-\tblood urea\r\n\t\t\tsc\t\t-\tserum creatinine\r\n\t\t\tsod\t\t-\tsodium\r\n\t\t\tpot\t\t-\tpotassium\r\n\t\t\themo\t\t-\themoglobin\r\n\t\t\tpcv\t\t-\tpacked cell volume\r\n\t\t\twc\t\t-\twhite blood cell count\r\n\t\t\trc\t\t-\tred blood cell count\r\n\t\t\thtn\t\t-\thypertension\r\n\t\t\tdm\t\t-\tdiabetes mellitus\r\n\t\t\tcad\t\t-\tcoronary artery disease\r\n\t\t\tappet\t\t-\tappetite\r\n\t\t\tpe\t\t-\tpedal edema\r\n\t\t\tane\t\t-\tanemia\r\n\t\t\tclass\t\t-\tclass\t', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'We use 24 + class = 25 ( 11  numeric ,14  nominal)\r\n1.Age(numerical)\r\n  \t  \tage in years\r\n \t2.Blood Pressure(numerical)\r\n\t       \tbp in mm/Hg\r\n \t3.Specific Gravity(nominal)\r\n\t  \tsg - (1.005,1.010,1.015,1.020,1.025)\r\n \t4.Albumin(nominal)\r\n\t\tal - (0,1,2,3,4,5)\r\n \t5.Sugar(nominal)\r\n\t\tsu - (0,1,2,3,4,5)\r\n \t6.Red Blood Cells(nominal)\r\n\t\trbc - (normal,abnormal)\r\n \t7.Pus Cell (nominal)\r\n\t\tpc - (normal,abnormal)\r\n \t8.Pus Cell clumps(nominal)\r\n\t\tpcc - (present,notpresent)\r\n \t9.Bacteria(nominal)\r\n\t\tba  - (present,notpresent)\r\n \t10.Blood Glucose Random(numerical)\t\t\r\n\t\tbgr in mgs/dl\r\n \t11.Blood Urea(numerical)\t\r\n\t\tbu in mgs/dl\r\n \t12.Serum Creatinine(numerical)\t\r\n\t\tsc in mgs/dl\r\n \t13.Sodium(numerical)\r\n\t\tsod in mEq/L\r\n \t14.Potassium(numerical)\t\r\n\t\tpot in mEq/L\r\n \t15.Hemoglobin(numerical)\r\n\t\themo in gms\r\n \t16.Packed  Cell Volume(numerical)\r\n \t17.White Blood Cell Count(numerical)\r\n\t\twc in cells/cumm\r\n \t18.Red Blood Cell Count(numerical)\t\r\n\t\trc in millions/cmm\r\n \t19.Hypertension(nominal)\t\r\n\t\thtn - (yes,no)\r\n \t20.Diabetes Mellitus(nominal)\t\r\n\t\tdm - (yes,no)\r\n \t21.Coronary Artery Disease(nominal)\r\n\t\tcad - (yes,no)\r\n \t22.Appetite(nominal)\t\r\n\t\tappet - (good,poor)\r\n \t23.Pedal Edema(nominal)\r\n\t\tpe - (yes,no)\t\r\n \t24.Anemia(nominal)\r\n\t\tane - (yes,no)\r\n \t25.Class (nominal)\t\t\r\n\t\tclass - (ckd,notckd)', 'citation': None}}

In [5]:
# variable information
print(chronic_kidney_disease.variables)

     name     role         type demographic              description  \
0     age  Feature      Integer         Age                     None
1      bp  Feature      Integer        None           blood pressure
2      sg  Feature  Categorical        None         specific gravity
3      al  Feature  Categorical        None                  albumin
4      su  Feature  Categorical        None                    sugar
5     rbc  Feature       Binary        None          red blood cells
6      pc  Feature       Binary        None                 pus cell
7     pcc  Feature       Binary        None          pus cell clumps
8      ba  Feature       Binary        None                 bacteria
9     bgr  Feature      Integer        None     blood glucose random
10     bu  Feature      Integer        None               blood urea
11     sc  Feature   Continuous        None         serum creatinine
12    sod  Feature      Integer        None                   sodium
13    pot  Feature   Continuous        None                potassium
14   hemo  Feature   Continuous        None               hemoglobin
15    pcv  Feature      Integer        None       packed cell volume
16   wbcc  Feature      Integer        None   white blood cell count
17   rbcc  Feature   Continuous        None     red blood cell count
18    htn  Feature       Binary        None             hypertension
19     dm  Feature       Binary        None        diabetes mellitus
20    cad  Feature       Binary        None  coronary artery disease
21  appet  Feature       Binary        None                 appetite
22     pe  Feature       Binary        None              pedal edema
23    ane  Feature       Binary        None                   anemia
24  class   Target       Binary        None           ckd or not ckd

           units missing_values
0           year            yes
1          mm/Hg            yes
2           None            yes
3           None            yes
4           None            yes
5           None            yes
6           None            yes
7           None            yes
8           None            yes
9         mgs/dl            yes
10        mgs/dl            yes
11        mgs/dl            yes
12         mEq/L            yes
13         mEq/L            yes
14           gms            yes
15          None            yes
16     cells/cmm            yes
17  millions/cmm            yes
18          None            yes
19          None            yes
20          None            yes
21          None            yes
22          None            yes
23          None            yes
24          None             no

In [1]:
import pandas as pd
import numpy as np  
from sklearn.impute import SimpleImputer

In [3]:
from ucimlrepo import fetch_ucirepo

# Fetch the dataset
chronic_kidney_disease = fetch_ucirepo(id=336)

# Extract features and targets
X = chronic_kidney_disease.data.features 
y = chronic_kidney_disease.data.targets

# Load the data into a DataFrame
df = X.copy()

# Check the first few rows of the original data
print("Original Data (First few rows):")
print(df.head())

Original Data (First few rows):
    age    bp     sg   al   su     rbc  ...  htn   dm cad  appet   pe  ane
0  48.0  80.0  1.020  1.0  0.0     NaN  ...  yes  yes  no   good   no   no
1   7.0  50.0  1.020  4.0  0.0     NaN  ...   no   no  no   good   no   no
2  62.0  80.0  1.010  2.0  3.0  normal  ...   no  yes  no   poor   no  yes
3  48.0  70.0  1.005  4.0  0.0  normal  ...  yes   no  no   poor  yes  yes
4  51.0  80.0  1.010  2.0  0.0  normal  ...   no   no  no   good   no   no

[5 rows x 24 columns]

In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from ucimlrepo import fetch_ucirepo

# Fetch the dataset
chronic_kidney_disease = fetch_ucirepo(id=336)

# Convert features into a DataFrame and add the target column
df = pd.DataFrame(chronic_kidney_disease.data.features)
df['class'] = chronic_kidney_disease.data.targets

# Print the first few rows of the data
print("First few rows:")
print(df.head())

First few rows:
    age    bp     sg   al   su     rbc  ...   dm cad appet   pe  ane  class
0  48.0  80.0  1.020  1.0  0.0     NaN  ...  yes  no  good   no   no    ckd
1   7.0  50.0  1.020  4.0  0.0     NaN  ...   no  no  good   no   no    ckd
2  62.0  80.0  1.010  2.0  3.0  normal  ...  yes  no  poor   no  yes    ckd
3  48.0  70.0  1.005  4.0  0.0  normal  ...   no  no  poor  yes  yes    ckd
4  51.0  80.0  1.010  2.0  0.0  normal  ...   no  no  good   no   no    ckd

[5 rows x 25 columns]

In [5]:
# Iterate over the columns
for column in df.columns:
    if df[column].dtype == 'object':  # Check if the column is categorical
        # Fill missing values with the most frequent value (mode)
        df[column] = df[column].fillna(df[column].mode()[0])
    else:  # If the column is numerical
        # Fill missing values with the median value
        df[column] = df[column].fillna(df[column].median())

# Print the missing values after handling
print("Missing values after handling:\n", df.isnull().sum())

# Display the first few rows of the updated DataFrame
import matplotlib.pyplot as plt
from IPython.display import display

display(df.head())

Missing values after handling:
 age      0
bp       0
sg       0
al       0
su       0
rbc      0
pc       0
pcc      0
ba       0
bgr      0
bu       0
sc       0
sod      0
pot      0
hemo     0
pcv      0
wbcc     0
rbcc     0
htn      0
dm       0
cad      0
appet    0
pe       0
ane      0
class    0
dtype: int64

    age    bp     sg   al   su     rbc  ...   dm cad appet   pe  ane  class
0  48.0  80.0  1.020  1.0  0.0  normal  ...  yes  no  good   no   no    ckd
1   7.0  50.0  1.020  4.0  0.0  normal  ...   no  no  good   no   no    ckd
2  62.0  80.0  1.010  2.0  3.0  normal  ...  yes  no  poor   no  yes    ckd
3  48.0  70.0  1.005  4.0  0.0  normal  ...   no  no  poor  yes  yes    ckd
4  51.0  80.0  1.010  2.0  0.0  normal  ...   no  no  good   no   no    ckd

[5 rows x 25 columns]

In [6]:
# List of columns to be mapped
binary_columns = ['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'class']

# Check unique values in each binary column
for column in binary_columns:
    print(f"{column}: {df[column].unique()}")  # Corrected parenthesis

    # Strip string values if needed
    df[column] = df[column].map(lambda x: x.strip() if isinstance(x, str) else x)

# Binary mappings for categorical columns
binary_mappings = {
    'rbc': {'normal': 0, 'abnormal': 1},
    'pc': {'normal': 0, 'abnormal': 1},
    'pcc': {'notpresent': 0, 'present': 1},
    'ba': {'notpresent': 0, 'present': 1},
    'htn': {'no': 0, 'yes': 1},
    'dm': {'no': 0, 'yes': 1},
    'cad': {'no': 0, 'yes': 1},
    'appet': {'poor': 0, 'good': 1},
    'pe': {'no': 0, 'yes': 1},
    'ane': {'no': 0, 'yes': 1},
    'class': {'notckd': 0, 'ckd': 1}
}

# Applying the binary mappings to the DataFrame
for column, mapping in binary_mappings.items():
    df[column] = df[column].map(mapping)

# Print the first few rows to check the changes
print(df.head())

rbc: ['normal' 'abnormal']
pc: ['normal' 'abnormal']
pcc: ['notpresent' 'present']
ba: ['notpresent' 'present']
htn: ['yes' 'no']
dm: ['yes' 'no' '\tno']
cad: ['no' 'yes']
appet: ['good' 'poor']
pe: ['no' 'yes']
ane: ['no' 'yes']
class: ['ckd' 'ckd\t' 'notckd']
    age    bp     sg   al   su  rbc  pc  ...  htn  dm  cad  appet  pe  ane  class
0  48.0  80.0  1.020  1.0  0.0    0   0  ...    1   1    0      1   0    0      1
1   7.0  50.0  1.020  4.0  0.0    0   0  ...    0   0    0      1   0    0      1
2  62.0  80.0  1.010  2.0  3.0    0   0  ...    0   1    0      0   0    1      1
3  48.0  70.0  1.005  4.0  0.0    0   1  ...    1   0    0      0   1    1      1
4  51.0  80.0  1.010  2.0  0.0    0   0  ...    0   0    0      1   0    0      1

[5 rows x 25 columns]

In [7]:
import numpy as np
from scipy.stats import zscore

# Assuming 'df' is the DataFrame
# Calculate the Z-scores for all numerical columns
z_scores = np.abs(zscore(df.select_dtypes(include=['float64', 'int64'])))  # Only numerical columns

# Define the threshold for outliers (e.g., Z-score > 3)
threshold = 3

# Identify outliers by checking where Z-scores are above the threshold
outliers = (z_scores > threshold)

# Remove rows with any outliers
df_no_outliers = df[~outliers.any(axis=1)]  # '~' is used to negate the boolean mask

# Print the shape of the original and cleaned DataFrame
print(f"Original DataFrame shape: {df.shape}")
print(f"Cleaned DataFrame shape: {df_no_outliers.shape}")

# Show the cleaned DataFrame
from IPython.display import display
display(df_no_outliers.head())

Original DataFrame shape: (400, 25)
Cleaned DataFrame shape: (313, 25)

    age    bp     sg   al   su  rbc  pc  ...  htn  dm  cad  appet  pe  ane  class
0  48.0  80.0  1.020  1.0  0.0    0   0  ...    1   1    0      1   0    0      1
1   7.0  50.0  1.020  4.0  0.0    0   0  ...    0   0    0      1   0    0      1
3  48.0  70.0  1.005  4.0  0.0    0   1  ...    1   0    0      0   1    1      1
4  51.0  80.0  1.010  2.0  0.0    0   0  ...    0   0    0      1   0    0      1
5  60.0  90.0  1.015  3.0  0.0    0   0  ...    1   1    0      1   1    0      1

[5 rows x 25 columns]

In [8]:
from sklearn.preprocessing import MinMaxScaler

# Identify binary columns (values are only 0 or 1)
binary_columns = [col for col in df.columns if df[col].nunique() == 2]

# Identify non-binary numeric columns (exclude binary columns)
non_binary_columns = [col for col in df.select_dtypes(include=['float64', 'int64']).columns if col not in binary_columns]

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Apply MinMaxScaler only to non-binary numeric columns
df[non_binary_columns] = scaler.fit_transform(df[non_binary_columns])

# Print the scaled dataset (non-binary columns only)
print("Scaled dataset (non-binary columns only):")
print(df.head())

Scaled dataset (non-binary columns only):
        age        bp    sg   al   su  rbc  ...  dm  cad  appet  pe  ane  class
0  0.522727  0.230769  0.75  0.2  0.0    0  ...   1    0      1   0    0      1
1  0.056818  0.000000  0.75  0.8  0.0    0  ...   0    0      1   0    0      1
2  0.681818  0.230769  0.25  0.4  0.6    0  ...   1    0      0   0    1      1
3  0.522727  0.153846  0.00  0.8  0.0    0  ...   0    0      0   1    1      1
4  0.556818  0.230769  0.25  0.4  0.0    0  ...   0    0      1   0    0      1

[5 rows x 25 columns]

In [9]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import numpy as np

# Example data (replace with your dataset)
X = np.random.rand(400, 24)  # Replace with your feature data
y = np.random.randint(2, size=400)  # Replace with your target labels

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the MLP Classifier
mlp = MLPClassifier(
    hidden_layer_sizes=(10,),  # One hidden layer with 10 neurons
    activation='relu',         # Activation function for the hidden layer
    solver='adam',             # Optimizer
    max_iter=500,              # Maximum number of iterations
    random_state=42
)

# Train the model
mlp.fit(X_train, y_train)

# Make predictions
y_pred = mlp.predict(X_test)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[23 10]
 [22 25]]

Classification Report:
              precision    recall  f1-score   support

           0       0.51      0.70      0.59        33
           1       0.71      0.53      0.61        47

    accuracy                           0.60        80
   macro avg       0.61      0.61      0.60        80
weighted avg       0.63      0.60      0.60        80

c:\Users\Dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(